(function(){
  const esc=window.escapeHtml||((v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])));
  const $=id=>document.getElementById(id);
  const nowYear=()=>new Date().getFullYear();
  const statusLabels={planned:'مبرمج',in_progress:'قيد التنفيذ',completed:'منجز',postponed:'مؤجل',cancelled:'ملغى'};
  let cache=[];

  function injectStyles(){if($('annualPlanStyles'))return;const s=document.createElement('style');s.id='annualPlanStyles';s.textContent=`
    .annual-stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:14px 0}.annual-stat{background:#fff;border:1px solid #dce8e6;border-radius:16px;padding:14px}.annual-stat b{font-size:24px;color:#0f766e;display:block}.annual-stat span{font-size:11px;color:#6b7f7b}.annual-toolbar{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.annual-toolbar label{min-width:150px}.annual-table-wrap{overflow:auto}.annual-table{width:100%;border-collapse:collapse;min-width:980px}.annual-table th,.annual-table td{padding:10px;border-bottom:1px solid #e6efed;text-align:right;vertical-align:top}.annual-table th{font-size:11px;color:#49635e;background:#f7faf9}.annual-table td{font-size:12px}.annual-status{display:inline-flex;padding:5px 9px;border-radius:999px;background:#eaf5f3;color:#0f766e;font-weight:800;font-size:10px}.annual-status.completed{background:#e7f8ee;color:#17663a}.annual-status.postponed{background:#fff4d8;color:#8a6300}.annual-status.cancelled{background:#fde9e9;color:#9f2b2b}.annual-actions{display:flex;gap:6px;flex-wrap:wrap}.annual-actions button{padding:6px 9px;font-size:10px}.annual-budget{font-weight:800}.annual-calendar{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:12px}.annual-month{border:1px solid #dce8e6;border-radius:14px;padding:12px;background:#fff}.annual-month h4{margin:0 0 7px}.annual-month small{color:#718682}.annual-month ul{padding-right:18px;margin:8px 0 0}.annual-month li{margin:5px 0;font-size:11px}@media(max-width:900px){.annual-stats{grid-template-columns:repeat(2,1fr)}.annual-calendar{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.annual-stats,.annual-calendar{grid-template-columns:1fr}}
    @media print{body>*:not(main){display:none!important}.topbar,.tabs,.editor,.annual-toolbar,.annual-actions{display:none!important}.tab-panel{display:none!important}[data-panel="annual-plan"]{display:block!important}.panel{box-shadow:none!important;border:0!important}.annual-table{min-width:0;font-size:9px}}
  `;document.head.appendChild(s)}

  function buildUI(){if($('annualPlanPanel'))return;injectStyles();const tabs=$('tabs');if(!tabs)return;
    const tab=document.createElement('button');tab.dataset.tab='annual-plan';tab.textContent='البرمجة السنوية';tabs.prepend(tab);
    const panel=document.createElement('section');panel.id='annualPlanPanel';panel.className='tab-panel hidden';panel.dataset.panel='annual-plan';panel.innerHTML=`
      <div class="content-stack">
        <section class="panel"><div class="list-head"><div><span class="badge">التخطيط السنوي</span><h2>البرمجة السنوية للأنشطة</h2><p>تخطيط أنشطة الجمعية وتتبع وضعية التنفيذ والميزانية التقديرية على مدار السنة.</p></div><button id="annualPrint" type="button" class="secondary">طباعة البرمجة</button></div>
          <div class="annual-toolbar"><label>السنة<input id="annualYearFilter" type="number" min="2000" max="2100"></label><label>الحالة<select id="annualStatusFilter"><option value="">كل الحالات</option><option value="planned">مبرمج</option><option value="in_progress">قيد التنفيذ</option><option value="completed">منجز</option><option value="postponed">مؤجل</option><option value="cancelled">ملغى</option></select></label><label>بحث<input id="annualSearch" type="search" placeholder="عنوان، محور، مسؤول..."></label><button id="annualRefresh" type="button" class="secondary">تحديث</button></div>
          <div id="annualStats" class="annual-stats"></div><div id="annualCalendar" class="annual-calendar"></div>
        </section>
        <div class="admin-grid report-grid">
          <section class="panel editor"><div class="section-title"><div><span class="badge">نشاط مبرمج</span><h2 id="annualFormTitle">إضافة نشاط إلى البرمجة</h2></div><button id="annualNew" class="secondary" type="button">+ نشاط جديد</button></div>
            <form id="annualForm"><input id="annualId" type="hidden"><div class="two"><label>السنة<input id="annualYear" type="number" min="2000" max="2100" required></label><label>الحالة<select id="annualStatus"><option value="planned">مبرمج</option><option value="in_progress">قيد التنفيذ</option><option value="completed">منجز</option><option value="postponed">مؤجل</option><option value="cancelled">ملغى</option></select></label></div>
              <label>عنوان النشاط<input id="annualTitle" required maxlength="220"></label><div class="two"><label>نوع النشاط<input id="annualCategory" list="annualCategories" required><datalist id="annualCategories"><option value="تربوي"><option value="تكويني"><option value="ثقافي"><option value="اجتماعي"><option value="رياضي"><option value="بيئي"><option value="رقمي"><option value="تحسيسي"><option value="حملة"><option value="لقاء أو ندوة"><option value="زيارة ميدانية"><option value="رحلة"><option value="معرض"><option value="مسابقة"></datalist></label><label>المحور / المجال<input id="annualAxis" maxlength="180" placeholder="مثال: التربية، الشباب، البيئة..."></label></div>
              <div class="two"><label>تاريخ البداية<input id="annualStart" type="date"></label><label>تاريخ النهاية<input id="annualEnd" type="date"></label></div><label>الفترة أو الشهر<input id="annualPeriod" maxlength="120" placeholder="مثال: شتنبر 2026 أو الدورة الأولى"></label>
              <div class="two"><label>المكان<input id="annualLocation" maxlength="180"></label><label>الفئة المستهدفة<input id="annualTarget" maxlength="220"></label></div><label>الأهداف<textarea id="annualObjectives" rows="3"></textarea></label><label>النتائج المنتظرة<textarea id="annualExpected" rows="3"></textarea></label>
              <div class="two"><label>المسؤول عن التنفيذ<input id="annualResponsible" maxlength="180"></label><label>الشركاء<input id="annualPartners" maxlength="240"></label></div><label>الميزانية التقديرية (درهم)<input id="annualBudget" type="number" min="0" step="0.01" value="0"></label><label>ملاحظات<textarea id="annualNotes" rows="3"></textarea></label>
              <div class="actions"><button type="submit">حفظ في البرمجة</button><button id="annualCancel" type="button" class="secondary">إلغاء</button></div><p id="annualMsg" class="msg"></p></form>
          </section>
          <section class="panel list-panel"><div class="list-head"><div><h2>قائمة الأنشطة المبرمجة</h2><p>يمكن تعديل الحالة أثناء تقدم التنفيذ.</p></div></div><div id="annualList"><p>جارٍ التحميل...</p></div></section>
        </div>
      </div>`;
    $('adminView').appendChild(panel);bind();resetForm();
  }

  function v(id){return ($(id)?.value||'').trim()}
  function n(id){return Math.max(0,Number($(id)?.value)||0)}
  function payload(){return {year:Number(v('annualYear')),title:v('annualTitle'),category:v('annualCategory')||'عام',axis:v('annualAxis'),start_date:v('annualStart')||null,end_date:v('annualEnd')||null,period_label:v('annualPeriod'),location:v('annualLocation'),target_group:v('annualTarget'),objectives:v('annualObjectives'),expected_results:v('annualExpected'),responsible:v('annualResponsible'),partners:v('annualPartners'),estimated_budget:n('annualBudget'),status:v('annualStatus')||'planned',notes:v('annualNotes')}}
  function resetForm(){if(!$('annualForm'))return;$('annualForm').reset();$('annualId').value='';$('annualYear').value=v('annualYearFilter')||nowYear();$('annualStatus').value='planned';$('annualBudget').value=0;$('annualFormTitle').textContent='إضافة نشاط إلى البرمجة';$('annualMsg').textContent=''}

  async function load(){const box=$('annualList');if(!box)return;box.innerHTML='<p>جارٍ تحميل البرمجة...</p>';const {data,error}=await client.from('annual_activity_plan').select('*').order('year',{ascending:false}).order('start_date',{ascending:true,nullsFirst:false}).order('id',{ascending:true});if(error){box.innerHTML='<div class="empty">تعذر تحميل البرمجة السنوية.</div>';return}cache=data||[];render()}
  function rows(){const y=Number(v('annualYearFilter'))||nowYear(),st=v('annualStatusFilter'),q=v('annualSearch').toLowerCase();return cache.filter(r=>Number(r.year)===y&&(!st||r.status===st)&&(!q||[r.title,r.category,r.axis,r.location,r.target_group,r.responsible,r.partners].some(x=>String(x||'').toLowerCase().includes(q))))}
  function fmtDate(d){return d?new Date(d+'T12:00:00').toLocaleDateString('ar-MA'):'—'}
  function render(){const rs=rows();const totalBudget=rs.reduce((a,r)=>a+Number(r.estimated_budget||0),0),done=rs.filter(r=>r.status==='completed').length,progress=rs.filter(r=>r.status==='in_progress').length,planned=rs.filter(r=>r.status==='planned').length;
    $('annualStats').innerHTML=`<div class="annual-stat"><b>${rs.length}</b><span>إجمالي الأنشطة</span></div><div class="annual-stat"><b>${planned}</b><span>مبرمجة</span></div><div class="annual-stat"><b>${progress}</b><span>قيد التنفيذ</span></div><div class="annual-stat"><b>${done}</b><span>منجزة</span></div><div class="annual-stat"><b>${totalBudget.toLocaleString('ar-MA',{maximumFractionDigits:2})}</b><span>الميزانية التقديرية بالدرهم</span></div>`;
    renderCalendar(rs);
    const box=$('annualList');if(!rs.length){box.innerHTML='<div class="empty">لا توجد أنشطة مطابقة لهذه السنة أو التصفية.</div>';return}
    box.innerHTML=`<div class="annual-table-wrap"><table class="annual-table"><thead><tr><th>النشاط</th><th>الفترة</th><th>المحور</th><th>الفئة</th><th>المسؤول</th><th>الميزانية</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody>${rs.map(r=>`<tr><td><strong>${esc(r.title)}</strong><br><small>${esc(r.category||'')}</small></td><td>${r.period_label?esc(r.period_label):`${fmtDate(r.start_date)}${r.end_date?' ← '+fmtDate(r.end_date):''}`}</td><td>${esc(r.axis||'—')}</td><td>${esc(r.target_group||'—')}</td><td>${esc(r.responsible||'—')}</td><td class="annual-budget">${Number(r.estimated_budget||0).toLocaleString('ar-MA',{maximumFractionDigits:2})} د.م</td><td><span class="annual-status ${r.status}">${statusLabels[r.status]||r.status}</span></td><td><div class="annual-actions"><button data-annual-edit="${r.id}">تعديل</button><button class="danger" data-annual-delete="${r.id}">حذف</button></div></td></tr>`).join('')}</tbody></table></div>`}
  function renderCalendar(rs){const names=['يناير','فبراير','مارس','أبريل','ماي','يونيو','يوليوز','غشت','شتنبر','أكتوبر','نونبر','دجنبر'];const groups=Array.from({length:12},()=>[]);rs.forEach(r=>{if(r.start_date){const m=Number(String(r.start_date).slice(5,7))-1;if(m>=0&&m<12)groups[m].push(r)}});$('annualCalendar').innerHTML=groups.map((g,i)=>`<div class="annual-month"><h4>${names[i]}</h4><small>${g.length} نشاط</small>${g.length?`<ul>${g.slice(0,5).map(r=>`<li>${esc(r.title)}</li>`).join('')}${g.length>5?`<li>+ ${g.length-5} أخرى</li>`:''}</ul>`:''}</div>`).join('')}
  function fill(r){$('annualId').value=r.id;$('annualYear').value=r.year;$('annualTitle').value=r.title||'';$('annualCategory').value=r.category||'';$('annualAxis').value=r.axis||'';$('annualStart').value=r.start_date||'';$('annualEnd').value=r.end_date||'';$('annualPeriod').value=r.period_label||'';$('annualLocation').value=r.location||'';$('annualTarget').value=r.target_group||'';$('annualObjectives').value=r.objectives||'';$('annualExpected').value=r.expected_results||'';$('annualResponsible').value=r.responsible||'';$('annualPartners').value=r.partners||'';$('annualBudget').value=r.estimated_budget||0;$('annualStatus').value=r.status||'planned';$('annualNotes').value=r.notes||'';$('annualFormTitle').textContent='تعديل النشاط المبرمج';$('annualForm').scrollIntoView({behavior:'smooth',block:'start'})}
  async function save(e){e.preventDefault();const msg=$('annualMsg');msg.textContent='جارٍ الحفظ...';try{const p=payload();if(!p.year||!p.title)throw new Error('أدخل السنة وعنوان النشاط.');const id=v('annualId');const q=id?client.from('annual_activity_plan').update(p).eq('id',id):client.from('annual_activity_plan').insert(p);const {error}=await q;if(error)throw error;msg.textContent='تم حفظ النشاط في البرمجة السنوية.';resetForm();await load()}catch(err){msg.textContent='تعذر الحفظ: '+(err.message||'خطأ غير معروف')}}
  async function del(id){if(!confirm('هل تريد حذف هذا النشاط من البرمجة السنوية؟'))return;const {error}=await client.from('annual_activity_plan').delete().eq('id',id);if(error){alert('تعذر حذف النشاط.');return}await load()}
  function bind(){
    $('annualForm').addEventListener('submit',save);$('annualNew').addEventListener('click',resetForm);$('annualCancel').addEventListener('click',resetForm);$('annualRefresh').addEventListener('click',load);$('annualPrint').addEventListener('click',()=>window.print());
    ['annualYearFilter','annualStatusFilter','annualSearch'].forEach(id=>$(id).addEventListener(id==='annualSearch'?'input':'change',render));
    $('annualList').addEventListener('click',e=>{const eb=e.target.closest('[data-annual-edit]');if(eb){const r=cache.find(x=>String(x.id)===String(eb.dataset.annualEdit));if(r)fill(r);return}const db=e.target.closest('[data-annual-delete]');if(db)del(db.dataset.annualDelete)});
  }
  async function init(){buildUI();$('annualYearFilter').value=nowYear();await load()}
  window.addEventListener('admin-auth-ready',init);if(window.currentAdminProfile)init();
})();
