(function(){
  const esc=window.escapeHtml||((v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])));
  const $=id=>document.getElementById(id);
  const nowYear=()=>new Date().getFullYear();
  const statusLabels={planned:'مبرمج',in_progress:'قيد التنفيذ',completed:'منجز',postponed:'مؤجل',cancelled:'ملغى'};
  const monthNames=['يناير','فبراير','مارس','أبريل','ماي','يونيو','يوليوز','غشت','شتنبر','أكتوبر','نونبر','دجنبر'];
  let cache=[];

  const starterActivities=[
    [1,'لقاء «عام جديد… مشروع جديد»','لقاء أو ندوة','تنمية الذات','الشباب واليافعون','مساعدة المستفيدين على تحديد أولوياتهم وأهدافهم السنوية.','خطة أولية واضحة لكل مشارك.'],
    [1,'ورشة تحديد الأهداف وبناء المشروع الشخصي','تكويني','التوجيه','الشباب','تنمية مهارة التخطيط الشخصي وتحويل الطموحات إلى أهداف قابلة للتنفيذ.','إعداد خطط شخصية مبسطة للمستفيدين.'],
    [1,'دورة أساسيات الحاسوب والإنترنت','رقمي','المهارات الرقمية','المبتدئون','إكساب المشاركين أساسيات استعمال الحاسوب والإنترنت بشكل آمن وعملي.','تحسن المهارات الرقمية الأساسية.'],
    [1,'يوم رياضي وترفيهي','رياضي','الرياضة والتنشيط','الأطفال والشباب','تعزيز الاندماج والعمل الجماعي عبر أنشطة رياضية وترفيهية.','رفع المشاركة والتفاعل بين المستفيدين.'],
    [2,'حملة الوقاية من التنمر الإلكتروني','تحسيسي','المواطنة الرقمية','اليافعون','التوعية بمخاطر التنمر الإلكتروني وأساليب الوقاية والتبليغ.','رفع الوعي بالسلوك الرقمي الآمن.'],
    [2,'ورشة التصميم باستخدام Canva','رقمي','المهارات الرقمية','الشباب','تعليم مبادئ التصميم البصري وإنتاج محتوى رقمي بسيط.','إنتاج تصاميم رقمية من طرف المشاركين.'],
    [2,'نادي القراءة والحوار','ثقافي','الثقافة','جميع المستفيدين','تنمية عادة القراءة والقدرة على التعبير والحوار واحترام الرأي الآخر.','جلسة قراءة ونقاش تفاعلية.'],
    [2,'مبادرة تضامنية محلية','اجتماعي','التضامن','الأسر والشباب','ترسيخ قيم التضامن والعمل التطوعي داخل المجتمع المحلي.','تنفيذ مبادرة تضامنية بمشاركة الشباب.'],
    [3,'ملتقى المرأة والفتاة','لقاء أو ندوة','التمكين','الفتيات والنساء','دعم الثقة بالنفس وإبراز فرص التعلم والتمكين والمبادرة.','مشاركة نسائية أوسع وتبادل تجارب ملهمة.'],
    [3,'ورشة مهارات التواصل والثقة بالنفس','تكويني','تنمية الذات','الشباب','تطوير التواصل الإيجابي والثقة بالنفس والعرض أمام الآخرين.','تحسن مهارات التواصل لدى المشاركين.'],
    [3,'ورشة التصوير وصناعة الفيديو','رقمي','الإعلام الرقمي','الشباب','تعريف الشباب بأساسيات التصوير وبناء فيديو قصير هادف.','إنتاج فيديوهات قصيرة من إنجاز المستفيدين.'],
    [3,'مسابقة ثقافية بين المستفيدين','مسابقة','الثقافة','الشباب','تحفيز التعلم الجماعي وتنمية الرصيد الثقافي بطريقة تفاعلية.','مشاركة فرق شبابية في مسابقة ثقافية.'],
    [4,'حملة نظافة وتشجير','حملة','البيئة','سكان الحي والشباب','تعزيز السلوك البيئي والمشاركة في تحسين الفضاء المحلي.','تنفيذ تدخل ميداني للنظافة أو التشجير.'],
    [4,'ورشة إعادة التدوير','تكويني','البيئة والإبداع','الأطفال والشباب','تنمية الوعي بإعادة الاستعمال وتحويل المخلفات إلى منتجات نافعة.','إنتاج نماذج وأعمال معاد تدويرها.'],
    [4,'زيارة مؤسسة أو مقاولة','زيارة ميدانية','التوجيه المهني','الشباب','تقريب الشباب من بيئة العمل والتعرف على المهن والمهارات المطلوبة.','زيارة مهنية موثقة واستفادة المشاركين من تجربة ميدانية.'],
    [4,'لقاء «اكتشف مهنتك»','لقاء أو ندوة','التوجيه المهني','الشباب','تعريف المشاركين بمسارات مهنية متنوعة من خلال لقاء مباشر مع مهنيين.','توسيع معرفة الشباب بالخيارات المهنية.'],
    [5,'ملتقى المهن والمسارات المهنية','معرض','الإدماج المهني','الشباب','ربط الشباب بالمهن والتكوينات والفرص المتاحة وبناء تصور مهني واقعي.','استفادة المشاركين من أروقة ولقاءات توجيهية.'],
    [5,'ورشة كتابة السيرة الذاتية','تكويني','التشغيل','الشباب','تمكين المشاركين من إعداد سيرة ذاتية واضحة وملائمة للفرص المهنية.','إعداد سير ذاتية قابلة للاستعمال.'],
    [5,'محاكاة مقابلات العمل','تكويني','التشغيل','الشباب','التدرب على تقديم الذات والإجابة عن أسئلة مقابلات العمل.','تنفيذ مقابلات تجريبية مع تغذية راجعة.'],
    [5,'دوري رياضي للجمعية','رياضي','الرياضة','الشباب','تقوية روح الفريق والانضباط والتنافس الإيجابي.','تنظيم دوري بمشاركة فرق من المستفيدين.'],
    [6,'معرض مشاريع المستفيدين','معرض','الإبداع','جميع المستفيدين','تثمين إنتاجات المستفيدين وإبراز تطور مهاراتهم أمام الأسر والشركاء.','عرض مشاريع وأعمال منجزة خلال المرحلة.'],
    [6,'مسابقة الابتكار الرقمي','مسابقة','الرقمنة','الشباب','تحفيز توظيف الأدوات الرقمية لحل مشكلات أو إنتاج أفكار مبتكرة.','نماذج أو مشاريع رقمية شبابية.'],
    [6,'ورشة الذكاء الاصطناعي للمبتدئين','رقمي','الذكاء الاصطناعي','الشباب','التعريف بمبادئ الذكاء الاصطناعي واستعمالاته التعليمية والمهنية المسؤولة.','قدرة المشاركين على استعمال أدوات AI في مهام بسيطة.'],
    [6,'حفل نهاية المرحلة والتكريم','ثقافي','التثمين','المستفيدون والأسر','الاحتفاء بالإنجازات وتحفيز الاستمرارية والالتزام.','تكريم المشاركين وتوثيق حصيلة المرحلة.'],
    [7,'افتتاح برنامج نور الأمل الصيفي','لقاء أو ندوة','التنشيط الصيفي','الأطفال والشباب','إطلاق برنامج صيفي يجمع التعلم والترفيه والتفاعل المجتمعي.','انخراط المستفيدين في البرنامج الصيفي.'],
    [7,'ورشة المسرح والتعبير','ثقافي','الفنون','الأطفال والشباب','تنمية التعبير الشفهي والثقة والإبداع من خلال المسرح.','إنتاج مشهد أو عرض قصير.'],
    [7,'خرجة ثقافية أو تربوية','رحلة','الثقافة والترفيه','المستفيدون','توسيع الخبرة الثقافية والتعلم خارج فضاء الجمعية.','تنظيم خرجة تربوية موثقة.'],
    [7,'ألعاب رياضية وتحديات جماعية','رياضي','الرياضة','الشباب','تعزيز التعاون واللياقة وروح الفريق في أجواء صيفية.','مشاركة فعالة في تحديات رياضية جماعية.'],
    [8,'Digital Summer Camp','رقمي','الرقمنة','الشباب','تكثيف التعلم الرقمي خلال العطلة عبر ورشات تطبيقية قصيرة.','مشاريع رقمية صغيرة من إنجاز المشاركين.'],
    [8,'ورشة إنشاء المواقع الإلكترونية','رقمي','البرمجة','الشباب','تعريف الشباب بأساسيات بناء صفحات ومواقع ويب بسيطة.','إنجاز مواقع أو صفحات تجريبية.'],
    [8,'ورشة الموشن غرافيك','رقمي','الإبداع الرقمي','الشباب','تنمية مهارات الحركة البصرية وإنتاج مقاطع موشن بسيطة.','إنتاج أعمال موشن غرافيك قصيرة.'],
    [8,'تحدي صناعة المحتوى','مسابقة','صناعة المحتوى','الشباب','تنمية مهارات التخطيط والإنتاج والنشر المسؤول للمحتوى الرقمي.','إنتاج محتويات رقمية هادفة.'],
    [9,'حملة العودة إلى الدراسة','حملة','التربية','الأطفال والشباب','تشجيع الاستمرار في التعلم والعودة إلى الدراسة بعد العطلة.','وصول الحملة إلى الفئات المستهدفة وتوجيه الحالات المناسبة.'],
    [9,'حملة استقطاب المنقطعين عن الدراسة','حملة','الفرصة الثانية','الشباب المنقطعون عن الدراسة','التعريف بمسارات الفرصة الثانية والوصول إلى الشباب المنقطعين.','تسجيل وإحالة مستفيدين محتملين.'],
    [9,'أيام التوجيه والاستقبال','لقاء أو ندوة','المواكبة','المستفيدون الجدد','استقبال المسجلين الجدد وتقديم البرامج والقواعد ومسارات المواكبة.','اندماج أفضل للمستفيدين الجدد.'],
    [9,'اختبارات تحديد المستوى والميول','تربوي','التشخيص','المسجلون الجدد','تشخيص المستوى والميول لبناء مسارات تعلم وتوجيه أكثر ملاءمة.','ملفات تشخيص فردية للمستفيدين.'],
    [10,'إطلاق شهر التطوع والمواطنة','حملة','المواطنة','الشباب','تحفيز الشباب على المشاركة المدنية وخدمة المجتمع عبر مبادرات عملية.','إطلاق سلسلة مبادرات تطوعية خلال الشهر.'],
    [10,'ورشة حقوق وواجبات المواطن','تكويني','المواطنة','الشباب','تعزيز فهم الحقوق والمسؤوليات والسلوك المدني الإيجابي.','رفع الوعي بالمواطنة والمشاركة.'],
    [10,'زيارة مؤسسة اجتماعية','زيارة ميدانية','التضامن','الشباب','تعريف الشباب بالعمل الاجتماعي وتحفيزهم على التطوع المنظم.','تنفيذ زيارة ونشاط تطوعي مرتبط بها.'],
    [10,'يوم ثقافي وفني','ثقافي','الثقافة','المجتمع المحلي','فتح فضاء للتعبير الفني والتواصل بين الجمعية ومحيطها.','تنظيم عروض ومشاركات فنية متنوعة.'],
    [11,'أسبوع ريادة الأعمال','لقاء أو ندوة','ريادة الأعمال','الشباب','التعريف بثقافة المبادرة والعمل الحر ومراحل بناء مشروع صغير.','توليد اهتمام وأفكار أولية لدى المشاركين.'],
    [11,'ورشة من الفكرة إلى المشروع','تكويني','ريادة الأعمال','حاملو الأفكار','تحويل الأفكار إلى نماذج مشاريع مبسطة قابلة للدراسة والتطوير.','صياغة بطاقات أولية لأفكار مشاريع.'],
    [11,'ورشة التسويق الرقمي','رقمي','المهارات المهنية الرقمية','الشباب','تعريف الشباب بأساسيات التسويق الرقمي والتواصل مع الجمهور.','إعداد نماذج حملات تسويقية تجريبية.'],
    [11,'لقاء مع مقاولين وشباب ناجحين','لقاء أو ندوة','التوجيه','الشباب','تقريب تجارب واقعية في المبادرة والعمل والتعلم من قصص النجاح والتحديات.','تبادل خبرات وأسئلة مباشرة مع ضيوف مهنيين.'],
    [12,'حملة تضامنية شتوية','حملة','التضامن','الأسر المحتاجة','تنظيم مبادرة شتوية تضامنية تستجيب لحاجات محلية محددة.','وصول الدعم إلى المستفيدين المستهدفين.'],
    [12,'مسابقة أفضل مشروع شبابي','مسابقة','الابتكار','الشباب','تثمين أفضل المشاريع والأفكار المنجزة خلال السنة وتشجيع المبادرة.','اختيار وتقديم مشاريع شبابية متميزة.'],
    [12,'المنتدى السنوي لجمعية نور الأمل','لقاء أو ندوة','الشراكات','المؤسسات والشركاء','عرض التجربة السنوية وتقوية العلاقات مع الشركاء والفاعلين المحليين.','توسيع شبكة التواصل والشراكات.'],
    [12,'حفل الحصيلة السنوية والتكريم','ثقافي','الحكامة والتثمين','المستفيدون والأسر والشركاء','تقديم حصيلة السنة والاعتراف بمساهمات المستفيدين والمتطوعين والشركاء.','تقرير ختامي وحفل تكريم موثق.']
  ];

  function starterRows(year){const days=[5,12,19,26],perMonth={};return starterActivities.map(item=>{const month=item[0];perMonth[month]=(perMonth[month]||0)+1;const slot=perMonth[month]-1;const date=`${year}-${String(month).padStart(2,'0')}-${String(days[slot]||26).padStart(2,'0')}`;return {year,title:item[1],category:item[2],axis:item[3],start_date:date,end_date:null,period_label:`الأسبوع ${['الأول','الثاني','الثالث','الرابع'][slot]} - ${monthNames[month-1]} ${year}`,location:'',target_group:item[4],objectives:item[5],expected_results:item[6],responsible:'فريق جمعية نور الأمل',partners:'',estimated_budget:0,status:'planned',notes:'ضمن البرمجة السنوية المقترحة لجمعية نور الأمل.'}})}

  function injectStyles(){if($('annualPlanStyles'))return;const s=document.createElement('style');s.id='annualPlanStyles';s.textContent=`
    .annual-stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:14px 0}.annual-stat{background:#fff;border:1px solid #dce8e6;border-radius:16px;padding:14px}.annual-stat b{font-size:24px;color:#0f766e;display:block}.annual-stat span{font-size:11px;color:#6b7f7b}.annual-toolbar{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.annual-toolbar label{min-width:150px}.annual-table-wrap{overflow:auto}.annual-table{width:100%;border-collapse:collapse;min-width:980px}.annual-table th,.annual-table td{padding:10px;border-bottom:1px solid #e6efed;text-align:right;vertical-align:top}.annual-table th{font-size:11px;color:#49635e;background:#f7faf9}.annual-table td{font-size:12px}.annual-status{display:inline-flex;padding:5px 9px;border-radius:999px;background:#eaf5f3;color:#0f766e;font-weight:800;font-size:10px}.annual-status.completed{background:#e7f8ee;color:#17663a}.annual-status.postponed{background:#fff4d8;color:#8a6300}.annual-status.cancelled{background:#fde9e9;color:#9f2b2b}.annual-actions{display:flex;gap:6px;flex-wrap:wrap}.annual-actions button{padding:6px 9px;font-size:10px}.annual-budget{font-weight:800}.annual-calendar{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:12px}.annual-month{border:1px solid #dce8e6;border-radius:14px;padding:12px;background:#fff}.annual-month h4{margin:0 0 7px}.annual-month small{color:#718682}.annual-month ul{padding-right:18px;margin:8px 0 0}.annual-month li{margin:5px 0;font-size:11px}.annual-template-btn{font-weight:800}@media(max-width:900px){.annual-stats{grid-template-columns:repeat(2,1fr)}.annual-calendar{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.annual-stats,.annual-calendar{grid-template-columns:1fr}}
    @media print{body>*:not(main){display:none!important}.topbar,.tabs,.editor,.annual-toolbar,.annual-actions{display:none!important}.tab-panel{display:none!important}[data-panel="annual-plan"]{display:block!important}.panel{box-shadow:none!important;border:0!important}.annual-table{min-width:0;font-size:9px}}
  `;document.head.appendChild(s)}

  function buildUI(){if($('annualPlanPanel'))return;injectStyles();const tabs=$('tabs');if(!tabs)return;
    const tab=document.createElement('button');tab.dataset.tab='annual-plan';tab.textContent='البرمجة السنوية';tabs.prepend(tab);
    const panel=document.createElement('section');panel.id='annualPlanPanel';panel.className='tab-panel hidden';panel.dataset.panel='annual-plan';panel.innerHTML=`
      <div class="content-stack">
        <section class="panel"><div class="list-head"><div><span class="badge">التخطيط السنوي</span><h2>البرمجة السنوية للأنشطة</h2><p>تخطيط أنشطة الجمعية وتتبع وضعية التنفيذ والميزانية التقديرية على مدار السنة.</p></div><button id="annualPrint" type="button" class="secondary">طباعة البرمجة</button></div>
          <div class="annual-toolbar"><label>السنة<input id="annualYearFilter" type="number" min="2000" max="2100"></label><label>الحالة<select id="annualStatusFilter"><option value="">كل الحالات</option><option value="planned">مبرمج</option><option value="in_progress">قيد التنفيذ</option><option value="completed">منجز</option><option value="postponed">مؤجل</option><option value="cancelled">ملغى</option></select></label><label>بحث<input id="annualSearch" type="search" placeholder="عنوان، محور، مسؤول..."></label><button id="annualRefresh" type="button" class="secondary">تحديث</button><button id="annualTemplate" type="button" class="secondary annual-template-btn">إضافة نموذج 48 نشاطاً</button></div>
          <div id="annualStats" class="annual-stats"></div><div id="annualCalendar" class="annual-calendar"></div>
        </section>
        <div class="admin-grid report-grid">
          <section class="panel editor"><div class="section-title"><div><span class="badge">نشاط مبرمج</span><h2 id="annualFormTitle">إضافة نشاط إلى البرمجة</h2></div><button id="annualNew" class="secondary" type="button">+ نشاط جديد</button></div>
            <form id="annualForm"><input id="annualId" type="hidden"><div class="two"><label>السنة<input id="annualYear" type="number" min="2000" max="2100" required></label><label>الحالة<select id="annualStatus"><option value="planned">مبرمج</option><option value="in_progress">قيد التنفيذ</option><option value="completed">منجز</option><option value="postponed">مؤجل</option><option value="cancelled">ملغى</option></select></label></div>
              <label>عنوان النشاط<input id="annualTitle" required maxlength="220"></label><div class="two"><label>نوع النشاط<input id="annualCategory" list="annualCategories" required><datalist id="annualCategories"><option value="تربوي"><option value="تكويني"><option value="ثقافي"><option value="اجتماعي"><option value="رياضي"><option value="بيئي"><option value="رقمي"><option value="تحسيسي"><option value="حملة"><option value="لقاء أو ندوة"><option value="زيارة ميدانية"><option value="رحلة"><option value="معرض"><option value="مسابقة"></datalist></label><label>المحور / المجال<input id="annualAxis" maxlength="180" placeholder="مثال: التربية، الشباب، البيئة..."></label></div>
              <div class="two"><label>تاريخ البداية<input id="annualStart" type="date"></label><label>تاريخ النهاية<input id="annualEnd" type="date"></label></div><label>الفترة أو الشهر<input id="annualPeriod" maxlength="120" placeholder="مثال: شتنبر 2026 أو الدورة الأولى"></label>
              <div class="two"><label>المكان<input id="annualLocation" maxlength="180"></label><label>الفئة المستهدفة<input id="annualTarget" maxlength="220"></label></div><label>الأهداف<textarea id="annualObjectives" rows="3"></textarea></label><label>النتائج المنتظرة<textarea id="annualExpected" rows="3"></textarea></label>
              <div class="two"><label>المسؤول عن التنفيذ<input id="annualResponsible" maxlength="180"></label><label>الشركاء<input id="annualPartners" maxlength="240"></label></div><label>الميزانية التقديرية (درهم)<input id="annualBudget" type="number" min="0" step="0.01" value="0"></label><label>ملاحظات<textarea id="annualNotes" rows="3"></textarea></label>
              <div class="actions"><button type="submit">حفظ في البرمجة</button><button id="annualCancel" type="button" class="secondary">إلغاء</button></div><p id="annualMsg" class="msg"></p></form>
          </section>
          <section class="panel list-panel"><div class="list-head"><div><h2>قائمة الأنشطة المبرمجة</h2><p>يمكن تعديل الحالة أثناء تقدم التنفيذ.</p></div></div><div id="annualList"><p>جارٍ التحميل...</p></div></section>
        </div>
      </div>`;
    $('adminView').appendChild(panel);bind();resetForm();
  }

  function v(id){return ($(id)?.value||'').trim()}
  function n(id){return Math.max(0,Number($(id)?.value)||0)}
  function payload(){return {year:Number(v('annualYear')),title:v('annualTitle'),category:v('annualCategory')||'عام',axis:v('annualAxis'),start_date:v('annualStart')||null,end_date:v('annualEnd')||null,period_label:v('annualPeriod'),location:v('annualLocation'),target_group:v('annualTarget'),objectives:v('annualObjectives'),expected_results:v('annualExpected'),responsible:v('annualResponsible'),partners:v('annualPartners'),estimated_budget:n('annualBudget'),status:v('annualStatus')||'planned',notes:v('annualNotes')}}
  function resetForm(){if(!$('annualForm'))return;$('annualForm').reset();$('annualId').value='';$('annualYear').value=v('annualYearFilter')||nowYear();$('annualStatus').value='planned';$('annualBudget').value=0;$('annualFormTitle').textContent='إضافة نشاط إلى البرمجة';$('annualMsg').textContent=''}

  async function load(){const box=$('annualList');if(!box)return;box.innerHTML='<p>جارٍ تحميل البرمجة...</p>';const {data,error}=await client.from('annual_activity_plan').select('*').order('year',{ascending:false}).order('start_date',{ascending:true,nullsFirst:false}).order('id',{ascending:true});if(error){box.innerHTML='<div class="empty">تعذر تحميل البرمجة السنوية.</div>';return false}cache=data||[];render();return true}
  function rows(){const y=Number(v('annualYearFilter'))||nowYear(),st=v('annualStatusFilter'),q=v('annualSearch').toLowerCase();return cache.filter(r=>Number(r.year)===y&&(!st||r.status===st)&&(!q||[r.title,r.category,r.axis,r.location,r.target_group,r.responsible,r.partners].some(x=>String(x||'').toLowerCase().includes(q))))}
  function fmtDate(d){return d?new Date(d+'T12:00:00').toLocaleDateString('ar-MA'):'—'}
  function render(){const rs=rows();const totalBudget=rs.reduce((a,r)=>a+Number(r.estimated_budget||0),0),done=rs.filter(r=>r.status==='completed').length,progress=rs.filter(r=>r.status==='in_progress').length,planned=rs.filter(r=>r.status==='planned').length;
    $('annualStats').innerHTML=`<div class="annual-stat"><b>${rs.length}</b><span>إجمالي الأنشطة</span></div><div class="annual-stat"><b>${planned}</b><span>مبرمجة</span></div><div class="annual-stat"><b>${progress}</b><span>قيد التنفيذ</span></div><div class="annual-stat"><b>${done}</b><span>منجزة</span></div><div class="annual-stat"><b>${totalBudget.toLocaleString('ar-MA',{maximumFractionDigits:2})}</b><span>الميزانية التقديرية بالدرهم</span></div>`;
    renderCalendar(rs);
    const box=$('annualList');if(!rs.length){box.innerHTML='<div class="empty">لا توجد أنشطة مطابقة لهذه السنة أو التصفية.</div>';return}
    box.innerHTML=`<div class="annual-table-wrap"><table class="annual-table"><thead><tr><th>النشاط</th><th>الفترة</th><th>المحور</th><th>الفئة</th><th>المسؤول</th><th>الميزانية</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody>${rs.map(r=>`<tr><td><strong>${esc(r.title)}</strong><br><small>${esc(r.category||'')}</small></td><td>${r.period_label?esc(r.period_label):`${fmtDate(r.start_date)}${r.end_date?' ← '+fmtDate(r.end_date):''}`}</td><td>${esc(r.axis||'—')}</td><td>${esc(r.target_group||'—')}</td><td>${esc(r.responsible||'—')}</td><td class="annual-budget">${Number(r.estimated_budget||0).toLocaleString('ar-MA',{maximumFractionDigits:2})} د.م</td><td><span class="annual-status ${r.status}">${statusLabels[r.status]||r.status}</span></td><td><div class="annual-actions"><button data-annual-edit="${r.id}">تعديل</button><button class="danger" data-annual-delete="${r.id}">حذف</button></div></td></tr>`).join('')}</tbody></table></div>`}
  function renderCalendar(rs){const groups=Array.from({length:12},()=>[]);rs.forEach(r=>{if(r.start_date){const m=Number(String(r.start_date).slice(5,7))-1;if(m>=0&&m<12)groups[m].push(r)}});$('annualCalendar').innerHTML=groups.map((g,i)=>`<div class="annual-month"><h4>${monthNames[i]}</h4><small>${g.length} نشاط</small>${g.length?`<ul>${g.slice(0,5).map(r=>`<li>${esc(r.title)}</li>`).join('')}${g.length>5?`<li>+ ${g.length-5} أخرى</li>`:''}</ul>`:''}</div>`).join('')}
  function fill(r){$('annualId').value=r.id;$('annualYear').value=r.year;$('annualTitle').value=r.title||'';$('annualCategory').value=r.category||'';$('annualAxis').value=r.axis||'';$('annualStart').value=r.start_date||'';$('annualEnd').value=r.end_date||'';$('annualPeriod').value=r.period_label||'';$('annualLocation').value=r.location||'';$('annualTarget').value=r.target_group||'';$('annualObjectives').value=r.objectives||'';$('annualExpected').value=r.expected_results||'';$('annualResponsible').value=r.responsible||'';$('annualPartners').value=r.partners||'';$('annualBudget').value=r.estimated_budget||0;$('annualStatus').value=r.status||'planned';$('annualNotes').value=r.notes||'';$('annualFormTitle').textContent='تعديل النشاط المبرمج';$('annualForm').scrollIntoView({behavior:'smooth',block:'start'})}
  async function save(e){e.preventDefault();const msg=$('annualMsg');msg.textContent='جارٍ الحفظ...';try{const p=payload();if(!p.year||!p.title)throw new Error('أدخل السنة وعنوان النشاط.');const id=v('annualId');const q=id?client.from('annual_activity_plan').update(p).eq('id',id):client.from('annual_activity_plan').insert(p);const {error}=await q;if(error)throw error;await load();resetForm();msg.textContent='تم حفظ النشاط في البرمجة السنوية.'}catch(err){msg.textContent='تعذر الحفظ: '+(err.message||'خطأ غير معروف')}}
  async function del(id){if(!confirm('هل تريد حذف هذا النشاط من البرمجة السنوية؟'))return;const {error}=await client.from('annual_activity_plan').delete().eq('id',id);if(error){alert('تعذر حذف النشاط.');return}await load()}
  async function importTemplate(silent=false){const year=Number(v('annualYearFilter'))||nowYear();const existingTitles=new Set(cache.filter(r=>Number(r.year)===year).map(r=>String(r.title||'').trim()));const missing=starterRows(year).filter(r=>!existingTitles.has(r.title));if(!missing.length){if(!silent)alert(`البرمجة المقترحة لسنة ${year} موجودة بالفعل.`);return}if(!silent&&!confirm(`سيتم إضافة ${missing.length} نشاطاً مقترحاً إلى برمجة سنة ${year}. هل تريد المتابعة؟`))return;const btn=$('annualTemplate');if(btn){btn.disabled=true;btn.textContent='جارٍ الإضافة...'}const {error}=await client.from('annual_activity_plan').insert(missing);if(btn){btn.disabled=false;btn.textContent='إضافة نموذج 48 نشاطاً'}if(error){if(!silent)alert('تعذر إضافة النموذج السنوي: '+error.message);return}await load();if(!silent)alert(`تمت إضافة ${missing.length} نشاطاً إلى برمجة سنة ${year}.`)}
  function bind(){
    $('annualForm').addEventListener('submit',save);$('annualNew').addEventListener('click',resetForm);$('annualCancel').addEventListener('click',resetForm);$('annualRefresh').addEventListener('click',load);$('annualPrint').addEventListener('click',()=>window.print());$('annualTemplate').addEventListener('click',()=>importTemplate(false));
    ['annualYearFilter','annualStatusFilter','annualSearch'].forEach(id=>$(id).addEventListener(id==='annualSearch'?'input':'change',render));
    $('annualList').addEventListener('click',e=>{const eb=e.target.closest('[data-annual-edit]');if(eb){const r=cache.find(x=>String(x.id)===String(eb.dataset.annualEdit));if(r)fill(r);return}const db=e.target.closest('[data-annual-delete]');if(db)del(db.dataset.annualDelete)});
  }
  async function init(){buildUI();$('annualYearFilter').value=nowYear();const ok=await load();if(ok&&!cache.some(r=>Number(r.year)===nowYear()))await importTemplate(true)}
  window.addEventListener('admin-auth-ready',init);if(window.currentAdminProfile)init();
})();