const menu=document.getElementById('menu');const nav=document.getElementById('navlinks');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));document.getElementById('year').textContent=new Date().getFullYear();

const labels={education:'تربية',training:'تكوين',digital:'رقمنة',community:'مجتمعي'};let activities=[];
function render(filter='all'){const grid=document.getElementById('activityGrid');const list=filter==='all'?activities:activities.filter(x=>x.category===filter);if(!list.length){grid.innerHTML='<div class="loading">لا توجد أنشطة في هذا التصنيف حالياً.</div>';return}grid.innerHTML=list.map(x=>`<article class="activity-card"><img src="${x.image}" alt="${x.title}" loading="lazy"><div class="activity-body"><div class="activity-meta"><span class="activity-type">${labels[x.category]||'نشاط'}</span><span>${x.date}</span></div><h3>${x.title}</h3><p>${x.description}</p></div></article>`).join('')}
fetch('data/activities.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{activities=d;render()}).catch(()=>document.getElementById('activityGrid').innerHTML='<div class="loading">تعذر تحميل الأنشطة.</div>');
document.getElementById('filters')?.addEventListener('click',e=>{const b=e.target.closest('button[data-filter]');if(!b)return;document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});

const counters=document.querySelectorAll('[data-count]');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target,target=Number(el.dataset.count);let n=0;const t=setInterval(()=>{n++;el.textContent=Math.min(n,target);if(n>=target)clearInterval(t)},70);observer.unobserve(el)}),{threshold:.6});counters.forEach(x=>observer.observe(x));

document.getElementById('contactForm')?.addEventListener('submit',e=>{e.preventDefault();document.getElementById('formNote').textContent='النموذج جاهز من جهة الواجهة. سنربطه لاحقاً بالبريد أو بخدمة استقبال الرسائل.'});